services:
  nodejs-app:
    image: matt262810/deviceid-api-server:latest
    ports:
      - "3000:3000"
    container_name: nodejs
    links:
      - mongodb
    hostname: nodejs
    restart: always
    depends_on:
      - mongodb
     
  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    restart: always
