services:
  nodejs-app:
    image: docker.pkg.github.com/mattdierick/deviceid-api-server/deviceid-apiserver:latest
    ports:
      - "3000:3000"
    container_name: nodejs
    links:
      - mongodb
    hostname: nodejs
    depends_on:
      - mongodb
     
  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
